export const portfolioData = [
  // CUSTOM SOFTWARE
  {
    id: "s1",
    slug: "ebilling-wall-design-hub",
    title: "EBilling Wall Design Hub",
    client: "Wall Design Hub",
    category: "Custom Software",
    year: "2024",
    thumbnail: "/projects/wall-software.webp",
    images: ["/projects/wall-software.webp"],
    techStack: ["React", "Custom Engine"],
    results: [{ value: "100%", label: "Automation" }],
    liveUrl: "https://ebilling.walldesign.co.in/"
  },
  {
    id: "s2",
    slug: "freedom-sales-system",
    title: "Freedom - Sales Management System",
    client: "Freedom",
    category: "Custom Software",
    year: "2024",
    thumbnail: "/projects/freedom-software.webp",
    images: ["/projects/freedom-software.webp"],
    techStack: ["Node.js", "Cloud"],
    results: [{ value: "50%", label: "Efficiency Boost" }],
    liveUrl: "https://freedom.skydreamix.co.in/"
  },
  {
    id: "s3",
    slug: "lawful-software",
    title: "Lawful Software",
    client: "Lawful",
    category: "Custom Software",
    year: "2024",
    thumbnail: "/projects/lawful_software.webp",
    images: ["/projects/lawful_software.webp"],
    techStack: ["Enterprise Suite"],
    results: [{ value: "Secure", label: "Legal Archiving" }],
    liveUrl: "https://lawfulwork.skydreamix.co.in/"
  },

  // MOBILE
  {
    id: "m1",
    slug: "edgeprop-my-pro-agent",
    title: "EdgeProp: MY PRO Agent",
    client: "EdgeProp",
    category: "Mobile",
    year: "2024",
    thumbnail: "/projects/edgeprop.webp",
    images: ["/projects/edgeprop.webp"],
    techStack: ["Android", "Real Estate"],
    results: [{ value: "Top Red", label: "App Store" }],
    liveUrl: "https://play.google.com/store/apps/details?id=com.edgeprop.agent&pcampaignid=web_share"
  },
  {
    id: "m2",
    slug: "duoo-video-chat",
    title: "Duoo - Video Chat, Live Stream",
    client: "Duoo",
    category: "Mobile",
    year: "2024",
    thumbnail: "/projects/duoo.webp",
    images: ["/projects/duoo.webp"],
    techStack: ["Live Video", "WebRTC"],
    results: [{ value: "1M+", label: "Daily Active" }],
    liveUrl: "https://play.google.com/store/apps/details?id=com.melot.meta&pcampaignid=web_share"
  },

  // WEB & DIGITAL
  {
    id: "w1",
    slug: "wall-design-hub",
    title: "Wall Design Hub",
    client: "Wall Design Hub",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/wall-design.webp",
    images: ["/projects/wall-design.webp"],
    techStack: ["React", "GSAP"],
    results: [{ value: "High", label: "UX Rating" }],
    liveUrl: "https://www.walldesign.co.in/"
  },
  {
    id: "w2",
    slug: "the-calcutta-heritage",
    title: "The Calcutta Heritage",
    client: "The Calcutta Heritage",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/calcutta-heritage.webp",
    images: ["/projects/calcutta-heritage.webp"],
    techStack: ["Next.js", "Design"],
    results: [{ value: "4.8/5", label: "User Love" }],
    liveUrl: "https://thecalcuttaheritage.com/"
  },
  {
    id: "w3",
    slug: "lingashtakam",
    title: "Lingashtakam",
    client: "Lingashtakam",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/lingastakam.webp",
    images: ["/projects/lingastakam.webp"],
    techStack: ["Sanity", "Astro"],
    results: [{ value: "Fast", label: "Load Times" }],
    liveUrl: "https://lingashtakam.org/"
  },
  {
    id: "w4",
    slug: "rudraksh-online",
    title: "Rudraksh Online",
    client: "Rudraksh Online",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/rudraksh-online.webp",
    images: ["/projects/rudraksh-online.webp"],
    techStack: ["E-commerce", "Stripe"],
    results: [{ value: "99%", label: "Uptime" }],
    liveUrl: "https://rudrakshaonline.co.in/"
  },
  {
    id: "w5",
    slug: "reav-stone-hub",
    title: "Reav Stone Hub",
    client: "Reav Stone Hub",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/reav.webp",
    images: ["/projects/reav.webp"],
    techStack: ["Industrial", "Tailwind"],
    results: [{ value: "Premium", label: "Feel" }],
    liveUrl: "https://reavstonehub.com/"
  },
  {
    id: "w6",
    slug: "sspruch",
    title: "SSpruch",
    client: "SSpruch",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/stella.webp",
    images: ["/projects/stella.webp"],
    techStack: ["Minimalist", "Vite"],
    results: [{ value: "Sleek", label: "Performance" }],
    liveUrl: "https://www.sspruch.com/"
  },
  {
    id: "w7",
    slug: "bhagavat-project",
    title: "Bhagavat Project",
    client: "Bhagavat Project",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/bhagavat.webp",
    images: ["/projects/bhagavat.webp"],
    techStack: ["Spirituality", "React"],
    results: [{ value: "Peaceful", label: "UX" }],
    liveUrl: "https://bhagavatconsciousness.org/"
  },
  {
    id: "w8",
    slug: "santoor-kartoon",
    title: "Santoor Kartoon",
    client: "Santoor Kartoon",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/santoor.webp",
    images: ["/projects/santoor.webp"],
    techStack: ["Creative", "Canvas"],
    results: [{ value: "Fun", label: "Engagement" }],
    liveUrl: "https://sentoorkartoon.com/"
  },
  {
    id: "w9",
    slug: "baidick",
    title: "Baidick",
    client: "Baidick",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/baidick.webp",
    images: ["/projects/baidick.webp"],
    techStack: ["Business", "Portfolio"],
    results: [{ value: "Clean", label: "UI" }],
    liveUrl: "https://baidick.com/"
  },
  {
    id: "w10",
    slug: "arkinhouse-interior",
    title: "Arkinhouse Interior",
    client: "Arkinhouse Interior",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/arkin.webp",
    images: ["/projects/arkin.webp"],
    techStack: ["Interior Design", "3D"],
    results: [{ value: "Visual", label: "Excellence" }],
    liveUrl: "https://arkinhouse.com/"
  },
  {
    id: "w11",
    slug: "stella-angel",
    title: "Stella Angel - Beauty & Style Lounge",
    client: "Stella Angel",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/stella-angel.webp",
    images: ["/projects/stella-angel.webp"],
    techStack: ["Lifestyle", "Spa"],
    results: [{ value: "Elegant", label: "Touch" }],
    liveUrl: "https://www.stella-angel.de/"
  },
  {
    id: "w12",
    slug: "seven-wheels-driving-school",
    title: "Seven Wheels Driving School",
    client: "Seven Wheels Driving School",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/sevenwheelsdrivingschool.webp",
    images: ["/projects/sevenwheelsdrivingschool.webp"],
    techStack: ["Service", "Booking"],
    results: [{ value: "Simple", label: "Flow" }],
    liveUrl: "https://sevenwheelsdrivingschool.co.in/"
  },
  {
    id: "w13",
    slug: "kolldriver",
    title: "Kolldriver",
    client: "Kolldriver",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/kolldriver.webp",
    images: ["/projects/kolldriver.webp"],
    techStack: ["Transport", "App"],
    results: [{ value: "Fast", label: "Navigation" }],
    liveUrl: "https://kolldriver.in/"
  },
  {
    id: "w14",
    slug: "ad-dynamic",
    title: "AD Dynamic",
    client: "AD Dynamic",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/ad-dynamic.webp",
    images: ["/projects/ad-dynamic.webp"],
    techStack: ["Ads", "Marketing"],
    results: [{ value: "Data", label: "Driven" }],
    liveUrl: "https://www.ad-dynamic.com"
  },
  {
    id: "w15",
    slug: "lawful-tax-consultancy",
    title: "Lawful Tax Consultancy",
    client: "Lawful Tax Consultancy",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/consultancy.webp",
    images: ["/projects/consultancy.webp"],
    techStack: ["Finance", "Trust"],
    results: [{ value: "Secure", label: "Portal" }],
    liveUrl: "https://www.lawfultaxconsultancy.com/"
  },
  {
    id: "w16",
    slug: "perfection-india",
    title: "Perfection India Legal & Tax Services",
    client: "Perfection India",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/perfectionindia.webp",
    images: ["/projects/perfectionindia.webp"],
    techStack: ["Legal", "B2B"],
    results: [{ value: "Global", label: "Reach" }],
    liveUrl: "https://perfectionindia.com/"
  },
  {
    id: "w17",
    slug: "calcutta-junction",
    title: "Calcutta Junction",
    client: "Calcutta Junction",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/calcutta_junction.webp",
    images: ["/projects/calcutta_junction.webp"],
    techStack: ["Community", "News"],
    results: [{ value: "Local", label: "Favorite" }],
    liveUrl: "https://calcuttajunction.com/"
  },
  {
    id: "w18",
    slug: "resume-dost",
    title: "Resume Dost",
    client: "Resume Dost",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/resume_dost.webp",
    images: ["/projects/resume_dost.webp"],
    techStack: ["Job Hunt", "Next.js"],
    results: [{ value: "High", label: "Success" }],
    liveUrl: "https://resumedost.com/"
  },
  {
    id: "w19",
    slug: "mudrasathi",
    title: "Mudrasathi",
    client: "Mudrasathi",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/mudrasathi.webp",
    images: ["/projects/mudrasathi.webp"],
    techStack: ["Financial", "Consultant"],
    results: [{ value: "Solid", label: "Advice" }],
    liveUrl: "#"
  },
  {
    id: "w20",
    slug: "parindra-sur",
    title: "Parindra Sur",
    client: "Parindra Sur",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/parindra_portfolio.webp",
    images: ["/projects/parindra_portfolio.webp"],
    techStack: ["Music", "React"],
    results: [{ value: "Aesthetic", label: "Portfolio" }],
    liveUrl: "https://parindrasur.in/"
  },
  {
    id: "w21",
    slug: "news-website",
    title: "News Website",
    client: "News Media",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/news_site.webp",
    images: ["/projects/news_site.webp"],
    techStack: ["Broadcasting", "Live"],
    results: [{ value: "Informative", label: "Flow" }],
    liveUrl: "#"
  },
  {
    id: "w22",
    slug: "sahochorjo",
    title: "Sahochorjo",
    client: "Sahochorjo",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/sahochorjo.webp",
    images: ["/projects/sahochorjo.webp"],
    techStack: ["NGO", "Impact"],
    results: [{ value: "Helping", label: "Hands" }],
    liveUrl: "https://brandwizer.synergynexa.com/sahochorjo"
  },
  {
    id: "w23",
    slug: "prantik-bharat-yuvo",
    title: "Prantik Bharat Yuvo",
    client: "PBYUVO",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/pbyuvo.webp",
    images: ["/projects/pbyuvo.webp"],
    techStack: ["Youth", "Community"],
    results: [{ value: "Global", label: "Platform" }],
    liveUrl: "https://pbyuvo.com/"
  },
  {
    id: "w24",
    slug: "fortis-oxygen",
    title: "Fortis Oxygen Concentrator",
    client: "Fortis Oxygen",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/fortisoxygenconcentratoronrentbangalore.webp",
    images: ["/projects/fortisoxygenconcentratoronrentbangalore.webp"],
    techStack: ["Healthcare", "E-shop"],
    results: [{ value: "Reliable", label: "Source" }],
    liveUrl: "https://fortisoxygenconcentratoronrentbangalore.com/"
  },
  {
    id: "w25",
    slug: "covercanvas",
    title: "CoverCanvas",
    client: "CoverCanvas",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/covercanvas.webp",
    images: ["/projects/covercanvas.webp"],
    techStack: ["Design", "Tools"],
    results: [{ value: "Artistic", label: "Library" }],
    liveUrl: "https://covercanvas.in/"
  },
  {
    id: "w26",
    slug: "haritala-mobile-centre",
    title: "Haritala Mobile Centre",
    client: "Haritala Mobile",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/haritalamobilecentre.webp",
    images: ["/projects/haritalamobilecentre.webp"],
    techStack: ["Retail", "Phones"],
    results: [{ value: "Fast", label: "Catalog" }],
    liveUrl: "https://haritalamobilecentre.in/home/"
  },
  {
    id: "w27",
    slug: "a-womans-world-beauty",
    title: "A Woman's World Beauty",
    client: "A Woman's World",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/awomansworldbeauty.webp",
    images: ["/projects/awomansworldbeauty.webp"],
    techStack: ["Beauty", "Spa"],
    results: [{ value: "Elegant", label: "Experience" }],
    liveUrl: "https://awomansworldbeauty.com/"
  },
  {
    id: "w28",
    slug: "city-cuts-and-colours",
    title: "City Cuts and Colours",
    client: "City Cuts",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/citycutsandcolours.webp",
    images: ["/projects/citycutsandcolours.webp"],
    techStack: ["Salon", "Style"],
    results: [{ value: "Modern", label: "Vibe" }],
    liveUrl: "https://citycutsandcolours.in/"
  },
  {
    id: "w29",
    slug: "tally-solutions-me",
    title: "Tally Solutions ME",
    client: "Tally Solutions",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/tallysolutions-me.webp",
    images: ["/projects/tallysolutions-me.webp"],
    techStack: ["ERP", "Enterprise"],
    results: [{ value: "Perfect", label: "Fit" }],
    liveUrl: "https://tallysolutions-me.com/"
  },
  {
    id: "w30",
    slug: "monoranjan-seva-sadan",
    title: "Monoranjan Seva Sadan",
    client: "Monoranjan Seva",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/monoranjansevasadan.webp",
    images: ["/projects/monoranjansevasadan.webp"],
    techStack: ["Medical", "NGO"],
    results: [{ value: "Humble", label: "Impact" }],
    liveUrl: "https://monoranjansevasadan.com/"
  },
  {
    id: "w31",
    slug: "dr-indranil-halder",
    title: "Dr. Indranil Halder",
    client: "Dr. Indranil Halder",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/drindranilhalder.webp",
    images: ["/projects/drindranilhalder.webp"],
    techStack: ["Healthcare", "Profile"],
    results: [{ value: "Top", label: "Care" }],
    liveUrl: "https://drindranilhalder.co.in/"
  },
  {
    id: "w32",
    slug: "dr-barun-chakraborty",
    title: "Dr. Barun Chakraborty",
    client: "Dr. Barun Chakraborty",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/drbarunappointment.webp",
    images: ["/projects/drbarunappointment.webp"],
    techStack: ["Doctors", "App"],
    results: [{ value: "Booked", label: "Success" }],
    liveUrl: "https://drbarunappointment.in/"
  },
  {
    id: "w33",
    slug: "manju-medical-stores",
    title: "Manju Medical Stores",
    client: "Manju Medical",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/manjumedicalstores.webp",
    images: ["/projects/manjumedicalstores.webp"],
    techStack: ["Pharmacy", "Clean"],
    results: [{ value: "Safe", label: "Delivery" }],
    liveUrl: "https://manjumedicalstores.co.in/"
  },
  {
    id: "w34",
    slug: "tripura-digital",
    title: "Tripura Digital",
    client: "Tripura Digital",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/tripuradigital.webp",
    images: ["/projects/tripuradigital.webp"],
    techStack: ["Digital Media", "Ads"],
    results: [{ value: "Modern", label: "UI" }],
    liveUrl: "https://tripuradigital.com/"
  },
  {
    id: "w35",
    slug: "growfast-digital-solutions",
    title: "Growfast Digital Solutions",
    client: "Growfast",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/growfast.webp",
    images: ["/projects/growfast.webp"],
    techStack: ["Growth", "Agency"],
    results: [{ value: "Expert", label: "Advice" }],
    liveUrl: "https://growfastdigitalsolutions.com/"
  },
  {
    id: "w36",
    slug: "the-euphoria-spa",
    title: "The Euphoria Spa",
    client: "The Euphoria Spa",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/theeuphoriaspa.webp",
    images: ["/projects/theeuphoriaspa.webp"],
    techStack: ["Relaxation", "Pro"],
    results: [{ value: "Luxe", label: "Feel" }],
    liveUrl: "https://theeuphoriaspa.com/"
  },
  {
    id: "w37",
    slug: "debnath-construction",
    title: "Debnath Construction",
    client: "Debnath Construction",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/debnathconstruction.webp",
    images: ["/projects/debnathconstruction.webp"],
    techStack: ["Civil", "React"],
    results: [{ value: "Bold", label: "Design" }],
    liveUrl: "https://debnathconstruction.com/"
  },
  {
    id: "w38",
    slug: "maitreyee-ultrasonic-centre",
    title: "Maitreyee Ultrasonic Centre",
    client: "Maitreyee Ultrasonic",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/maitreyeeultrasoniccentre.webp",
    images: ["/projects/maitreyeeultrasoniccentre.webp"],
    techStack: ["Diagnostics", "Fast"],
    results: [{ value: "Reliable", label: "Reports" }],
    liveUrl: "https://maitreyeeultrasoniccentre.co.in/"
  },
  {
    id: "w39",
    slug: "talentedge",
    title: "TalentEdge",
    client: "TalentEdge",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/talentedge.webp",
    images: ["/projects/talentedge.webp"],
    techStack: ["Education", "LMS"],
    results: [{ value: "Smart", label: "Learning" }],
    liveUrl: "https://talentedge.covercanvas.in/"
  },
  {
    id: "w40",
    slug: "astrologer-aritriya-banerjee",
    title: "Astrologer Aritriya Banerjee",
    client: "Aritriya Banerjee",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/astrologeraritriyabanerjee.webp",
    images: ["/projects/astrologeraritriyabanerjee.webp"],
    techStack: ["Astrology", "Blog"],
    results: [{ value: "Insightful", label: "Tips" }],
    liveUrl: "https://astrologeraritriyabanerjee.in/"
  },
  {
    id: "w41",
    slug: "astrologer-s-kummar",
    title: "Astrologer S Kummar",
    client: "S Kummar",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/astrologerskummar.webp",
    images: ["/projects/astrologerskummar.webp"],
    techStack: ["Stars", "Daily"],
    results: [{ value: "Popular", label: "Choice" }],
    liveUrl: "https://astrologerskummar.com/"
  },
  {
    id: "w42",
    slug: "dr-veena-pani-acharya",
    title: "Dr. Veena Pani Acharya",
    client: "Dr. Veena Pani Acharya",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/drveenapaniacharya.webp",
    images: ["/projects/drveenapaniacharya.webp"],
    techStack: ["Medal", "Doc"],
    results: [{ value: "Trust", label: "Primary" }],
    liveUrl: "https://drveenapaniacharya.in/"
  },
  {
    id: "w43",
    slug: "rtel-online",
    title: "RTEL Online",
    client: "RTEL",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/rtelonline.webp",
    images: ["/projects/rtelonline.webp"],
    techStack: ["Telecom", "Next"],
    results: [{ value: "Global", label: "Sync" }],
    liveUrl: "https://rtelonline.com/"
  },
  {
    id: "w44",
    slug: "elite-properties-india",
    title: "Elite Properties India",
    client: "Elite Properties",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/elitepropertiesindia.webp",
    images: ["/projects/elitepropertiesindia.webp"],
    techStack: ["Real Estate", "Pro"],
    results: [{ value: "Elite", label: "Search" }],
    liveUrl: "https://elitepropertiesindia.in/"
  },
  {
    id: "w45",
    slug: "mdmizer",
    title: "MDMizer",
    client: "MDMizer",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/mdmizer.webp",
    images: ["/projects/mdmizer.webp"],
    techStack: ["Marketing", "Tool"],
    results: [{ value: "Data", label: "Rich" }],
    liveUrl: "https://mdmizer.in/"
  },
  {
    id: "w46",
    slug: "organo-market",
    title: "Organo Market",
    client: "Organo Market",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/organomarket.webp",
    images: ["/projects/organomarket.webp"],
    techStack: ["Organic", "Farm"],
    results: [{ value: "Fresh", label: "UI" }],
    liveUrl: "https://organomarket.in/"
  },
  {
    id: "w47",
    slug: "health-point-clinic",
    title: "Health Point Clinic",
    client: "Health Point",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/healthpointclinic.webp",
    images: ["/projects/healthpointclinic.webp"],
    techStack: ["Clinic", "App"],
    results: [{ value: "Modern", label: "Health" }],
    liveUrl: "https://healthpointclinic.net/"
  },
  {
    id: "w48",
    slug: "greenlands",
    title: "Greenlands",
    client: "Greenlands",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/greenlands.webp",
    images: ["/projects/greenlands.webp"],
    techStack: ["Nature", "Eco"],
    results: [{ value: "Pure", label: "Aesthetic" }],
    liveUrl: "https://greenlands.biz/"
  },
  {
    id: "w49",
    slug: "pb-jewellers",
    title: "PB Jewellers",
    client: "PB Jewellers",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/pbjewellers.webp",
    images: ["/projects/pbjewellers.webp"],
    techStack: ["Luxury", "Gems"],
    results: [{ value: "Shine", label: "UI" }],
    liveUrl: "https://pbjewellers.co.in/"
  },
  {
    id: "w50",
    slug: "fleet-flex-fitness",
    title: "Fleet Flex Fitness",
    client: "Fleet Flex",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/fleetflexfitness.webp",
    images: ["/projects/fleetflexfitness.webp"],
    techStack: ["Gym", "Pulse"],
    results: [{ value: "Strong", label: "Core" }],
    liveUrl: "https://fleetflexfitness.in/"
  },
  {
    id: "w51",
    slug: "dr-manindranath-sahoo",
    title: "Dr. Manindranath Sahoo",
    client: "Dr. Manindranath Sahoo",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/drmanindranathsahoo.webp",
    images: ["/projects/drmanindranathsahoo.webp"],
    techStack: ["Top Doc", "Vite"],
    results: [{ value: "Elite", label: "Trust" }],
    liveUrl: "https://drmanindranathsahoo.co.in/"
  },
  {
    id: "w52",
    slug: "elite-holiday-trip",
    title: "Elite Holiday Trip",
    client: "Elite Holiday Trip",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/eliteholidaytrip.webp",
    images: ["/projects/eliteholidaytrip.webp"],
    techStack: ["Travel", "Next"],
    results: [{ value: "Global", label: "Vibe" }],
    liveUrl: "https://eliteholidaytrip.com/"
  },
  {
    id: "w53",
    slug: "samya-samaj-foundation",
    title: "Samya Samaj Foundation",
    client: "Samya Samaj",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/samyasamaj.webp",
    images: ["/projects/samyasamaj.webp"],
    techStack: ["Foundation", "NGO"],
    results: [{ value: "Kind", label: "Impact" }],
    liveUrl: "https://www.samyasamaj.org/"
  },
  {
    id: "w54",
    slug: "rockstar-music-dance",
    title: "Rockstar Music & Dance",
    client: "Rockstar",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/rockstar.webp",
    images: ["/projects/rockstar.webp"],
    techStack: ["Studio", "Art"],
    results: [{ value: "Fun", label: "Vibe" }],
    liveUrl: "https://www.rockstarmusicdance.com/"
  },
  {
    id: "w55",
    slug: "ssbrush-digitex",
    title: "SSPRUSH (Digitex)",
    client: "Digitex",
    category: "Web & Digital",
    year: "2024",
    thumbnail: "/projects/sspruch.webp",
    images: ["/projects/sspruch.webp"],
    techStack: ["Enterprise", "B2B"],
    results: [{ value: "Modern", label: "Flow" }],
    liveUrl: "https://projects.synergynexa.com/digitex"
  },

  // GRAPHICS DESIGN
  {
    id: "g1",
    slug: "fb-lawful-tax",
    title: "Lawful Tax Consultancy FB",
    client: "Lawful Tax",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(1).webp",
    images: ["/projects/Facebook(1).webp"],
    techStack: ["Photoshop", "Branding"],
    results: [{ value: "Viral", label: "Reach" }],
    liveUrl: "#"
  },
  {
    id: "g2",
    slug: "fb-samya-samaj",
    title: "Samya Samaj Foundation FB",
    client: "Samya Samaj",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook.webp",
    images: ["/projects/Facebook.webp"],
    techStack: ["Illustrator", "Social"],
    results: [{ value: "Clean", label: "Design" }],
    liveUrl: "#"
  },
  {
    id: "g3",
    slug: "fb-freedom",
    title: "Freedom FB Design",
    client: "Freedom",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(2).webp",
    images: ["/projects/Facebook(2).webp"],
    techStack: ["Marketing", "Visuals"],
    results: [{ value: "Pro", label: "Look" }],
    liveUrl: "#"
  },
  {
    id: "g4",
    slug: "fb-smart-to-service",
    title: "Smart to Service FB",
    client: "Smart to Service",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(3).webp",
    images: ["/projects/Facebook(3).webp"],
    techStack: ["Digital", "Art"],
    results: [{ value: "Fresh", label: "Vibe" }],
    liveUrl: "#"
  },
  {
    id: "g5",
    slug: "fb-star-abacus",
    title: "Star Abacus Institution FB",
    client: "Star Abacus",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(4).webp",
    images: ["/projects/Facebook(4).webp"],
    techStack: ["Education", "Design"],
    results: [{ value: "Parent", label: "Approve" }],
    liveUrl: "#"
  },
  {
    id: "g6",
    slug: "fb-walldesign-hub",
    title: "Walldesign Hub FB",
    client: "Wall Design Hub",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(5).webp",
    images: ["/projects/Facebook(5).webp"],
    techStack: ["Interior", "Ads"],
    results: [{ value: "Creative", label: "Layout" }],
    liveUrl: "#"
  },
  {
    id: "g7",
    slug: "fb-sree-hair-skin",
    title: "Sree Hair & Skin Studio FB",
    client: "Sree Hair & Skin",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/Facebook(6).webp",
    images: ["/projects/Facebook(6).webp"],
    techStack: ["Beauty", "Brand"],
    results: [{ value: "Stylized", label: "Graphics" }],
    liveUrl: "#"
  },
  {
    id: "g8",
    slug: "ig-freedom",
    title: "Freedom Instagram",
    client: "Freedom",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/freedom.webp",
    images: ["/projects/freedom.webp"],
    techStack: ["Insta", "Grid"],
    results: [{ value: "High", label: "Engagement" }],
    liveUrl: "#"
  },
  {
    id: "g9",
    slug: "ig-walldesign-hub",
    title: "Walldesign Hub Instagram",
    client: "Wall Design Hub",
    category: "Graphics Design",
    year: "2024",
    thumbnail: "/projects/wall.webp",
    images: ["/projects/wall.webp"],
    techStack: ["Modern", "Aura"],
    results: [{ value: "Clean", label: "Feed" }],
    liveUrl: "#"
  }
];
